spring:
  ai:
    openai:
      api-key: ${DEEPSEEK_API_KEY}
      base-url: https://api.deepseek.com
#      api-key: ${ALIYUN_API_KEY}
#      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: deepseek-chat
#          model: qwen-omni-turbo
      embedding:
        base-url: https://dashscope.aliyuncs.com/compatible-mode
        api-key: ${ALIYUN_API_KEY}
        options:
          model: text-embedding-v3
          dimensions: 1024
    vectorstore:
      redis:
        index: spring_ai_index # 向量库索引名
        initialize-schema: true # 是否初始化向量库索引结构
        prefix: "doc:" # 向量库key前缀
  servlet:
    multipart:
      max-file-size: 104857600
      max-request-size: 104857600
#  data:
#    redis:
#      host: 192.168.239.132 # redis地址
  datasource:
    url: jdbc:mysql://192.168.239.132:3306/itheima?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&useServerPrepStmts=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.zjx.star.springai: debug
